const C=window.BOSMASA_CONFIG||{};const hasSB=C.SUPABASE_URL&&!C.SUPABASE_URL.startsWith('BURAYA_')&&C.SUPABASE_ANON_KEY&&!C.SUPABASE_ANON_KEY.startsWith('BURAYA_');const sb=hasSB?supabase.createClient(C.SUPABASE_URL,C.SUPABASE_ANON_KEY):null;
const state={view:'home',user:null,role:null,offers:JSON.parse(localStorage.getItem('bm_offers')||'null')||[
{id:'1',business:'Masa 34',category:'Restoran',title:'Ana yemekte %25 indirim',city:'İstanbul',expires:'45 dk',emoji:'🍽️',active:true,limit:20,used:8},
{id:'2',business:'Kahve Rotası',category:'Kafe',title:'İkinci kahve ücretsiz',city:'Kadıköy',expires:'32 dk',emoji:'☕',active:true,limit:15,used:5},
{id:'3',business:'Tatlı Durağı',category:'Tatlı',title:'Tüm tatlılarda %20',city:'Beşiktaş',expires:'1 sa',emoji:'🍰',active:true,limit:30,used:12}
],filter:'Tümü'};
const $=s=>document.querySelector(s);function save(){localStorage.setItem('bm_offers',JSON.stringify(state.offers))}function nav(v){state.view=v;render()}function layout(body){return `<div class="shell"><header class="topbar"><nav class="nav"><div class="brand"><span class="brandmark">BM</span>Boş Masa</div><div class="navlinks"><button class="navbtn ${state.view==='home'?'active':''}" onclick="nav('home')">Keşfet</button><button class="navbtn ${state.view==='business'?'active':''}" onclick="nav('business')">İşletme Paneli</button><button class="navbtn ${state.view==='admin'?'active':''}" onclick="nav('admin')">Yönetici</button><button class="btn secondary" onclick="openLogin()">${state.user?state.user:'Giriş Yap'}</button></div></nav></header>${body}<footer class="footer">© 2026 Boş Masa · Anlık fırsatlar, dolu masalar.</footer></div><div id="modalRoot"></div>`}
function render(){const body=state.view==='business'?businessView():state.view==='admin'?adminView():homeView();document.getElementById('app').innerHTML=layout(body)}
function homeView(){const cats=['Tümü','Restoran','Kafe','Tatlı'];const items=state.offers.filter(o=>o.active&&(state.filter==='Tümü'||o.category===state.filter));return `<main class="container"><section class="hero"><div><span class="badge">ANLIK FIRSATLAR</span><h1>Boş masa kalmasın.</h1><p>Yakınındaki restoran ve kafelerin süreli fırsatlarını keşfet, kodunu al ve mekânda kullan.</p><div><button class="btn primary" onclick="document.getElementById('offers').scrollIntoView({behavior:'smooth'})">Fırsatları Gör</button> <button class="btn secondary" onclick="nav('business')">İşletmeyim</button></div></div><div class="heroCard"><div class="badge">CANLI</div><h2 style="font-size:38px;margin:55px 0 8px">Bugün yakınında<br>${items.length} fırsat var</h2><p style="color:#f3d7c7">Kampanyalar süre ve kontenjanla sınırlıdır.</p></div></section><div class="search"><input id="q" placeholder="Mekân veya kampanya ara" oninput="searchOffers(this.value)"></div><div class="chips">${cats.map(c=>`<button class="chip ${state.filter===c?'active':''}" onclick="setFilter('${c}')">${c}</button>`).join('')}</div><section id="offers"><div class="sectionTitle"><h2>Aktif fırsatlar</h2><span class="muted">${items.length} sonuç</span></div><div class="grid" id="offerGrid">${items.map(card).join('')||'<div class="empty">Aktif kampanya bulunamadı.</div>'}</div></section></main>`}
function card(o){return `<article class="card"><div class="cover">${o.emoji}</div><div class="content"><div class="row"><b>${o.business}</b><span class="badge">${o.category}</span></div><div class="offer">${o.title}</div><div class="row"><span class="muted">📍 ${o.city}</span><span class="countdown">${o.expires} kaldı</span></div><p class="muted">${o.limit-o.used} kullanım hakkı kaldı</p><button class="btn primary" style="width:100%" onclick="claim('${o.id}')">Kodu Al</button></div></article>`}
function businessView(){return `<main class="container"><div class="panel"><aside class="sidebar"><button class="sidebtn active">Genel Bakış</button><button class="sidebtn" onclick="openCampaign()">Yeni Kampanya</button><button class="sidebtn">Kod Doğrula</button></aside><section><div class="notice">Bu panel gerçek Supabase bilgileri girildiğinde işletme hesabına özel çalışır. Şu an arayüz ve yerel test modu aktiftir.</div><div class="sectionTitle"><h2>İşletme Paneli</h2><button class="btn primary" onclick="openCampaign()">Kampanya Oluştur</button></div><div class="stats"><div class="stat"><span class="muted">Aktif kampanya</span><b>${state.offers.filter(x=>x.active).length}</b></div><div class="stat"><span class="muted">Toplam kullanım</span><b>${state.offers.reduce((a,b)=>a+b.used,0)}</b></div><div class="stat"><span class="muted">Görüntülenme</span><b>1.248</b></div><div class="stat"><span class="muted">Dönüşüm</span><b>%18</b></div></div><div class="sectionTitle"><h2>Kampanyalar</h2></div><table class="table"><thead><tr><th>İşletme</th><th>Kampanya</th><th>Durum</th><th>İşlem</th></tr></thead><tbody>${state.offers.map(o=>`<tr><td>${o.business}</td><td>${o.title}</td><td>${o.active?'Yayında':'Durduruldu'}</td><td><button class="btn secondary" onclick="toggleOffer('${o.id}')">${o.active?'Durdur':'Yayınla'}</button></td></tr>`).join('')}</tbody></table></section></div></main>`}
function adminView(){return `<main class="container"><div class="sectionTitle"><h2>Yönetici Paneli</h2><span class="badge">Boş Masa v1.0</span></div><div class="stats"><div class="stat"><span class="muted">Kullanıcı</span><b>1.024</b></div><div class="stat"><span class="muted">İşletme</span><b>86</b></div><div class="stat"><span class="muted">Aktif kampanya</span><b>${state.offers.filter(x=>x.active).length}</b></div><div class="stat"><span class="muted">Kod kullanımı</span><b>${state.offers.reduce((a,b)=>a+b.used,0)}</b></div></div><div class="sectionTitle"><h2>İşletme onayları</h2></div><table class="table"><thead><tr><th>İşletme</th><th>Şehir</th><th>Durum</th><th>İşlem</th></tr></thead><tbody><tr><td>Masa 34</td><td>İstanbul</td><td>Onaylı</td><td><button class="btn secondary">İncele</button></td></tr><tr><td>Kahve Rotası</td><td>Kadıköy</td><td>Bekliyor</td><td><button class="btn primary">Onayla</button></td></tr></tbody></table></main>`}
function setFilter(c){state.filter=c;render()}function searchOffers(q){q=q.toLowerCase();document.querySelectorAll('#offerGrid .card').forEach(el=>el.style.display=el.innerText.toLowerCase().includes(q)?'':'none')}
function claim(id){const o=state.offers.find(x=>x.id===id);const code='BM'+Math.random().toString(36).slice(2,8).toUpperCase();showModal(`<h2>${o.business}</h2><p>${o.title}</p><div class="codebox">${code}</div><p class="muted">Kodu işletme görevlisine göster. Tek kullanımlıktır.</p><button class="btn primary" style="width:100%" onclick="closeModal()">Tamam</button>`)}
function openLogin(){showModal(`<h2>Giriş yap</h2><input class="field" id="email" placeholder="E-posta"><input class="field" id="pass" type="password" placeholder="Şifre" style="margin-top:10px"><button class="btn primary" style="width:100%;margin-top:14px" onclick="login()">Giriş Yap</button><p class="muted">Supabase bağlanmadıysa demo giriş yapılır.</p>`)}
async function login(){const email=$('#email').value;if(sb){const {error}=await sb.auth.signInWithPassword({email,password:$('#pass').value});if(error)return alert(error.message)}state.user=email||'Kullanıcı';closeModal();render()}
function openCampaign(){showModal(`<h2>Yeni kampanya</h2><div class="formgrid"><input class="field" id="b" placeholder="İşletme adı"><select class="field" id="cat"><option>Restoran</option><option>Kafe</option><option>Tatlı</option></select></div><input class="field" id="t" placeholder="Kampanya başlığı" style="margin-top:10px"><div class="formgrid" style="margin-top:10px"><input class="field" id="city" placeholder="Şehir / İlçe"><input class="field" id="limit" type="number" placeholder="Kullanım limiti"></div><button class="btn primary" style="width:100%;margin-top:14px" onclick="addOffer()">Yayınla</button>`)}
async function addOffer(){const o={id:Date.now().toString(),business:$('#b').value||'Yeni İşletme',category:$('#cat').value,title:$('#t').value||'Yeni kampanya',city:$('#city').value||'İstanbul',expires:'1 sa',emoji:'🍽️',active:true,limit:Number($('#limit').value||20),used:0};state.offers.unshift(o);save();if(sb){await sb.from('campaigns').insert({title:o.title,category:o.category,city:o.city,usage_limit:o.limit,is_active:true})}closeModal();render()}
function toggleOffer(id){const o=state.offers.find(x=>x.id===id);o.active=!o.active;save();render()}function showModal(html){document.getElementById('modalRoot').innerHTML=`<div class="modal" onclick="if(event.target===this)closeModal()"><div class="modalbox">${html}</div></div>`}function closeModal(){document.getElementById('modalRoot').innerHTML=''}
render();
